modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "hierophantics"
version = "${version}"
displayName = "Hierophantics"
logoFile = "assets/hierophantics/icon.png"
authors = "Robotgiggle"
description = "An addon to Hex Casting that lets you work with extracted minds to create conditional hexes and merge villagers."

[[dependencies.hierophantics]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hierophantics]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hierophantics]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hierophantics]]
modId = "cloth_config"
mandatory = true
versionRange = "[${versions.cloth_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hierophantics]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting_dependency},)"
ordering = "NONE"
side = "BOTH"
